2021-12-29 12:59:49.118 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2092), thread 'MainThread' (139750478002480):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7f1a2ef86a60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7f1a2eb30dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7f1a2eb30ee0>
    └ <function Scaffold.run at 0x7f1a2ea49430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7f1a2ea49430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7f1a2fb9ac40>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7f1a2ef845e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7f1a2efcaee0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7f1a2efca5e0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7f1a2efca670>
               └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7f1a2efca700>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7f1a2efca8b0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7f1a2efc9160>
              └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7f1a2ea47fd0>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 13:06:36.905 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (1951), thread 'MainThread' (140441749584176):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fbb21f7ba60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fbb21b25dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fbb21b25ee0>
    └ <function Scaffold.run at 0x7fbb21a3e430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fbb21a3e430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fbb22b8db20>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fbb21f795e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fbb21fbfee0>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fbb21fbf5e0>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fbb21fbf670>
               └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fbb21fbf700>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fbb21fbf8b0>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fbb21fbe160>
              └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fbb21a3cd60>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 13:12:02.956 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2151), thread 'MainThread' (140484411164976):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fc510cbea60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fc51086adc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fc51086aee0>
    └ <function Scaffold.run at 0x7fc51077f430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fc51077f430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fc5118d2d00>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fc510cbc5e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fc510d01ee0>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fc510d015e0>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fc510d01670>
               └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fc510d01700>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fc510d018b0>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fc510d00160>
              └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fc51077df70>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 14:50:13.292 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (1922), thread 'MainThread' (140662242650416):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fee7860fa60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fee781badc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fee781baee0>
    └ <function Scaffold.run at 0x7fee780d1430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fee780d1430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fee79b46a90>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fee7860d5e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fee78652ee0>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fee786525e0>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fee78652670>
               └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fee78652700>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fee786528b0>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fee78651160>
              └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fee780cff10>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 14:52:04.393 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2093), thread 'MainThread' (140586310777136):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fdcca7c7a60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fdcca371dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fdcca371ee0>
    └ <function Scaffold.run at 0x7fdcca28a430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fdcca28a430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fdccbd50fd0>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fdcca7c55e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fdcca80bee0>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fdcca80b5e0>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fdcca80b670>
               └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fdcca80b700>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fdcca80b8b0>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fdcca80a160>
              └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fdcca288f40>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2023-12-09 08:42:47.572 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2023-12-09 08:42:47.642 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2023-12-09 21:03:08.723 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2025-07-25 08:55:21.492 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 08:55:22.213 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 08:55:22.217 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 08:55:22.219 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 10:51:36.893 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 10:51:37.513 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 10:51:37.567 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 10:51:37.569 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:20:45.301 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:20:45.939 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:20:45.953 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:20:45.955 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 21:06:04.339 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 21:06:04.340 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 21:06:04.343 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 21:06:04.343 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 08:53:41.036 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 08:53:42.044 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 08:53:42.080 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 08:53:42.082 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 10:44:28.912 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 10:44:29.720 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 10:44:29.722 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 10:44:29.724 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:18:44.513 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:18:44.669 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:18:44.703 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:18:44.714 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 21:00:59.965 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 21:00:59.967 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 21:00:59.968 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 21:00:59.969 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:00:44.056 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:00:44.669 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:00:44.674 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:00:44.677 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:19:41.753 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:19:41.754 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:19:41.908 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:19:41.910 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 21:02:19.695 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 21:02:19.697 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 21:02:19.702 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 21:02:19.703 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 08:59:32.401 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 08:59:33.109 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 08:59:33.116 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 08:59:33.131 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 11:05:19.101 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 11:05:19.244 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 11:05:19.291 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 11:05:19.293 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:21:54.063 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:21:54.177 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:21:54.179 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:21:54.181 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 21:09:04.052 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 21:09:04.054 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 21:09:04.055 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 21:09:04.057 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:01:07.676 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:01:07.869 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:01:07.882 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:01:07.918 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:22:11.508 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:22:11.707 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:22:11.710 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:22:11.712 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 21:10:04.364 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 21:10:04.368 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 21:10:04.369 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 21:10:04.370 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 08:56:25.416 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 08:56:25.952 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 08:56:26.018 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 08:56:26.021 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 10:57:32.579 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 10:57:32.614 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 10:57:32.620 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 10:57:32.632 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:22:02.822 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:22:03.443 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:22:03.447 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:22:03.460 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 21:09:24.715 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 21:09:24.718 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 21:09:24.721 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 21:09:24.727 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 08:56:13.063 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 08:56:13.335 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 08:56:13.369 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 08:56:13.372 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 10:56:40.276 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 10:56:40.533 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 10:56:40.537 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 10:56:40.538 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:19:53.743 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:19:54.375 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:19:54.380 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:19:54.382 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 21:07:14.343 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 21:07:14.347 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 21:07:14.347 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 21:07:14.348 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:02:42.763 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:02:42.878 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:02:42.893 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:02:42.937 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
